/**
 * Trader names and coin tickers chosen by the site's owner. Prices, trades and
 * results shown against them are made up.
 */

/** Methods for the eleven founding desks, in desk order. Names are drawn at random from TRADER_NAMES. */
export const STARTING_METHODS = ['permabull', 'trend', 'dip', 'sniper', 'diamond', 'fiver', 'intern', 'quant', 'stops', 'narrative', 'averager'] as const;

/** Every trader name. Founders, hires and replacements are all drawn from here at random. */
export const TRADER_NAMES = [
  "unipcs",
  "DumbCrayonEater",
  "Salem1299534",
  "AvgJoesCrypto",
  "theveeman",
  "The__Solstice",
  "brrrgrrrz",
  "ogle",
  "notanicecat69",
  "SolSwizzle",
  "RugDalio",
  "Chubbi230",
  "kyle",
  "lordarbiter",
  "CardinalSaint2",
  "motiyawerey",
  "0xdetweiler",
  "soby0x",
  "frankdegods",
  "0xAvast",
  "Aurelius0121",
  "aki11a",
  "econoar",
  "cryptoalbus",
  "Quanterty",
  "dreamloaderxo",
  "FullPinkYak",
  "justtesting",
  "jotagezin",
  "decu",
  "trunoest",
  "Cented",
  "Mr. Frog",
  "theo",
  "Kadenox",
  "Ducky",
  "Schoen",
  "Flames",
  "EustazZ",
  "Megga",
  "ban",
  "zeropnl",
  "radiance",
  "Cupsey",
  "Iced",
  "Clown",
  "LUKEY ✣",
  "Idontpaytaxes",
  "Wugi",
  "Jijo",
  "omar",
  "Lynk",
  "Dani",
  "0xEthan",
  "Daumen",
  "Nyhrox",
  "cap",
  "unprofitable",
  "Jack Duval",
  "Mitch",
  "Cooker",
  "jester",
  "MrSamo",
];

export type Theme = 'dogs' | 'cats' | 'critters' | 'agents' | 'culture';
export const THEMES: Theme[] = ['dogs', 'cats', 'critters', 'agents', 'culture'];
export const THEME_LABEL: Record<Theme, string> = {
  dogs: 'dog coins',
  cats: 'cat coins',
  critters: 'other animals',
  agents: 'agent coins',
  culture: 'internet culture',
};

/** Coins the desks watch. Every price, chart and trade on the site is made up. */
export const COINS: { ticker: string; theme: Theme }[] = [
  { ticker: "MBTC", theme: 'culture' },
  { ticker: "AI", theme: 'agents' },
  { ticker: "Tessa", theme: 'agents' },
  { ticker: "MICRO", theme: 'culture' },
  { ticker: "GREEN", theme: 'culture' },
  { ticker: "HALL", theme: 'culture' },
  { ticker: "VFX", theme: 'culture' },
  { ticker: "Jackass", theme: 'culture' },
  { ticker: "CHRISTA", theme: 'culture' },
  { ticker: "IMDT", theme: 'culture' },
  { ticker: "Sartun", theme: 'culture' },
  { ticker: "WFM", theme: 'culture' },
  { ticker: "SI", theme: 'agents' },
  { ticker: "Ajax", theme: 'culture' },
  { ticker: "INU", theme: 'dogs' },
  { ticker: "OpenSI", theme: 'agents' },
  { ticker: "ACTII", theme: 'agents' },
  { ticker: "KAI", theme: 'agents' },
  { ticker: "Kuma", theme: 'cats' },
  { ticker: "nip", theme: 'culture' },
  { ticker: "o/acc", theme: 'agents' },
  { ticker: "P/ACC", theme: 'agents' },
  { ticker: "1MBTC", theme: 'culture' },
  { ticker: "BANDIT", theme: 'culture' },
  { ticker: "BBL", theme: 'culture' },
  { ticker: "Collateral", theme: 'culture' },
  { ticker: "CRED", theme: 'culture' },
  { ticker: "CRIME", theme: 'culture' },
  { ticker: "CRIMECOIN", theme: 'culture' },
  { ticker: "CURVE", theme: 'culture' },
  { ticker: "DMI", theme: 'culture' },
  { ticker: "DOBBY", theme: 'dogs' },
  { ticker: "elephant", theme: 'critters' },
  { ticker: "GH", theme: 'culture' },
  { ticker: "GI", theme: 'agents' },
  { ticker: "Inuween", theme: 'dogs' },
  { ticker: "LONG", theme: 'culture' },
  { ticker: "OTTER", theme: 'critters' },
  { ticker: "P3jca", theme: 'culture' },
  { ticker: "Pair", theme: 'culture' },
  { ticker: "Pengpeng", theme: 'critters' },
  { ticker: "PUMPCHAN", theme: 'culture' },
  { ticker: "QI", theme: 'agents' },
  { ticker: "Ronald", theme: 'culture' },
  { ticker: "SE", theme: 'culture' },
  { ticker: "SICZAR", theme: 'agents' },
  { ticker: "SRI", theme: 'culture' },
  { ticker: "tail", theme: 'critters' },
  { ticker: "Uptober", theme: 'culture' },
  { ticker: "Yuri", theme: 'culture' },
  { ticker: "かのくん", theme: 'culture' },
  { ticker: "アイヌ", theme: 'culture' },
  { ticker: "backpack", theme: 'culture' },
  { ticker: ".si", theme: 'agents' },
  { ticker: "CI", theme: 'agents' },
  { ticker: "ELON", theme: 'culture' },
  { ticker: "JADOODOO", theme: 'culture' },
  { ticker: "Meridian", theme: 'culture' },
  { ticker: "☉", theme: 'culture' },
  { ticker: "Basin8", theme: 'culture' },
  { ticker: "BEAR", theme: 'critters' },
  { ticker: "BI", theme: 'agents' },
  { ticker: "BOB", theme: 'culture' },
  { ticker: "Breastcoin", theme: 'culture' },
  { ticker: "DARWIN", theme: 'agents' },
  { ticker: "Democrat", theme: 'culture' },
  { ticker: "DOTS", theme: 'culture' },
  { ticker: "gentoo", theme: 'critters' },
  { ticker: "HALLIN", theme: 'culture' },
  { ticker: "LKY", theme: 'culture' },
  { ticker: "MINTFOLIO", theme: 'culture' },
  { ticker: "PILL", theme: 'culture' },
  { ticker: "PUTIN", theme: 'culture' },
  { ticker: "PUTINU", theme: 'dogs' },
  { ticker: "Q4", theme: 'culture' },
  { ticker: "Quant", theme: 'agents' },
  { ticker: "Rocket", theme: 'culture' },
  { ticker: "SINGULARITY", theme: 'agents' },
  { ticker: ".COM", theme: 'culture' },
  { ticker: "1", theme: 'culture' },
  { ticker: "3/acc", theme: 'agents' },
  { ticker: "80085", theme: 'culture' },
  { ticker: "?", theme: 'culture' },
  { ticker: "@bot", theme: 'agents' },
  { ticker: "ANT", theme: 'critters' },
  { ticker: "APES", theme: 'critters' },
  { ticker: "Arthur", theme: 'culture' },
  { ticker: "BABYBOY", theme: 'culture' },
  { ticker: "BANDS", theme: 'culture' },
  { ticker: "Bastion", theme: 'culture' },
  { ticker: "BENJAMIN", theme: 'culture' },
  { ticker: "BLINGBOY", theme: 'culture' },
  { ticker: "Blob", theme: 'critters' },
  { ticker: "BLUEY", theme: 'culture' },
  { ticker: "Boobs", theme: 'culture' },
  { ticker: "BOT", theme: 'agents' },
  { ticker: "BOTFLY", theme: 'critters' },
  { ticker: "BOTSTAR", theme: 'agents' },
  { ticker: "Bread", theme: 'culture' },
  { ticker: "BREAST", theme: 'culture' },
  { ticker: "Breastinu", theme: 'dogs' },
  { ticker: "bryce", theme: 'culture' },
  { ticker: "BTC", theme: 'culture' },
  { ticker: "BUBBLE", theme: 'culture' },
  { ticker: "BUTTHOLE", theme: 'culture' },
  { ticker: "BWALLET", theme: 'culture' },
  { ticker: "CALLCAT", theme: 'cats' },
  { ticker: "CANDACE", theme: 'culture' },
  { ticker: "Caramelo", theme: 'culture' },
  { ticker: "Cat", theme: 'cats' },
  { ticker: "CATSANC", theme: 'cats' },
  { ticker: "CHIP", theme: 'agents' },
  { ticker: "CLAUDIA", theme: 'agents' },
  { ticker: "CN", theme: 'culture' },
  { ticker: "COM", theme: 'culture' },
  { ticker: "Cookie", theme: 'culture' },
  { ticker: "CPU", theme: 'agents' },
  { ticker: "CSFUN", theme: 'culture' },
  { ticker: "CURVEPILL", theme: 'culture' },
  { ticker: "CYFRIN", theme: 'culture' },
  { ticker: "detective", theme: 'culture' },
  { ticker: "DI", theme: 'agents' },
  { ticker: "DOMINO", theme: 'culture' },
  { ticker: "dotchain", theme: 'culture' },
  { ticker: "dotsi", theme: 'agents' },
  { ticker: "DOTSPAD", theme: 'culture' },
  { ticker: "Dotty", theme: 'culture' },
  { ticker: "duc", theme: 'critters' },
  { ticker: "DUCK", theme: 'critters' },
  { ticker: "e/pad", theme: 'culture' },
  { ticker: "ERRAND", theme: 'culture' },
  { ticker: "EVILAPE", theme: 'critters' },
  { ticker: "Ezo", theme: 'culture' },
  { ticker: "Factionalism", theme: 'culture' },
  { ticker: "FARGAM", theme: 'culture' },
  { ticker: "few", theme: 'culture' },
  { ticker: "FF", theme: 'culture' },
  { ticker: "FILLD", theme: 'culture' },
  { ticker: "FROGE", theme: 'critters' },
  { ticker: "FS", theme: 'culture' },
  { ticker: "Gaejuki", theme: 'culture' },
  { ticker: "ganadi", theme: 'culture' },
  { ticker: "GIGACHAD", theme: 'culture' },
  { ticker: "GND", theme: 'culture' },
  { ticker: "GrokSaw", theme: 'agents' },
  { ticker: "gs", theme: 'culture' },
  { ticker: "HardScope", theme: 'culture' },
  { ticker: "Hat", theme: 'culture' },
  { ticker: "HC", theme: 'culture' },
  { ticker: "HOOKERS", theme: 'culture' },
  { ticker: "HOTDOG", theme: 'dogs' },
  { ticker: "human", theme: 'agents' },
  { ticker: "ilb", theme: 'culture' },
  { ticker: "INUDEX", theme: 'culture' },
  { ticker: "inuininu", theme: 'dogs' },
  { ticker: "inusider", theme: 'dogs' },
  { ticker: "INUVESTMENT", theme: 'dogs' },
  { ticker: "IRL", theme: 'culture' },
  { ticker: "JADODOO", theme: 'culture' },
  { ticker: "jerome", theme: 'culture' },
  { ticker: "KASHED", theme: 'culture' },
  { ticker: "KEN", theme: 'culture' },
  { ticker: "KLED", theme: 'culture' },
  { ticker: "KRBPTY", theme: 'culture' },
  { ticker: "KTM", theme: 'culture' },
  { ticker: "Leo", theme: 'culture' },
  { ticker: "LI", theme: 'agents' },
  { ticker: "LIBRA2", theme: 'culture' },
  { ticker: "LinkedInu", theme: 'dogs' },
  { ticker: "LOCKIN", theme: 'culture' },
  { ticker: "lockеdinu", theme: 'dogs' },
  { ticker: "Malfoid", theme: 'culture' },
  { ticker: "MANY", theme: 'culture' },
  { ticker: "MEM", theme: 'culture' },
  { ticker: "MEME", theme: 'culture' },
  { ticker: "MEMELIFE", theme: 'culture' },
  { ticker: "MERRYMEN", theme: 'culture' },
  { ticker: "metamesk", theme: 'culture' },
  { ticker: "Mew", theme: 'cats' },
  { ticker: "MF", theme: 'culture' },
  { ticker: "MICRODOG", theme: 'dogs' },
  { ticker: "MICROVRAX", theme: 'culture' },
  { ticker: "MIDNIGHT", theme: 'culture' },
  { ticker: "Mochi", theme: 'critters' },
  { ticker: "MONEY", theme: 'culture' },
  { ticker: "MOONCAT", theme: 'cats' },
  { ticker: "Mosquito", theme: 'critters' },
  { ticker: "MOTH", theme: 'critters' },
  { ticker: "Motinu", theme: 'dogs' },
  { ticker: "MT", theme: 'culture' },
  { ticker: "Neko", theme: 'cats' },
  { ticker: "NGUIN", theme: 'critters' },
  { ticker: "NUVI", theme: 'culture' },
  { ticker: "OAI", theme: 'agents' },
  { ticker: "Odysseus", theme: 'culture' },
  { ticker: "OFY", theme: 'culture' },
  { ticker: "ONDOH", theme: 'culture' },
  { ticker: "PalmCivet", theme: 'critters' },
  { ticker: "Pare", theme: 'culture' },
  { ticker: "Partyhat", theme: 'culture' },
  { ticker: "Pawbook", theme: 'critters' },
  { ticker: "Periwinkle", theme: 'culture' },
  { ticker: "PF", theme: 'culture' },
  { ticker: "Pigeonman", theme: 'critters' },
  { ticker: "PITTBULL", theme: 'dogs' },
  { ticker: "POND", theme: 'culture' },
  { ticker: "Pongpong", theme: 'culture' },
  { ticker: "pre", theme: 'culture' },
  { ticker: "PROMI", theme: 'culture' },
  { ticker: "PTK", theme: 'culture' },
  { ticker: "PUMP", theme: 'culture' },
  { ticker: "PUMPCARDS", theme: 'culture' },
  { ticker: "PUMPCOIN", theme: 'culture' },
  { ticker: "pumplined?", theme: 'culture' },
  { ticker: "Pumptober", theme: 'culture' },
  { ticker: "QCAT", theme: 'cats' },
  { ticker: "qDOG", theme: 'dogs' },
  { ticker: "QRS", theme: 'culture' },
  { ticker: "Quantavious", theme: 'agents' },
  { ticker: "qubit", theme: 'agents' },
  { ticker: "Quest", theme: 'culture' },
  { ticker: "railed", theme: 'culture' },
  { ticker: "RAYZE", theme: 'culture' },
  { ticker: "REPLICATOR", theme: 'cats' },
  { ticker: "reserve", theme: 'culture' },
  { ticker: "REV", theme: 'culture' },
  { ticker: "RICH", theme: 'culture' },
  { ticker: "runG", theme: 'culture' },
  { ticker: "RUNNER", theme: 'culture' },
  { ticker: "S", theme: 'culture' },
  { ticker: "SALVADOR", theme: 'culture' },
  { ticker: "Saw", theme: 'culture' },
  { ticker: "SBB", theme: 'culture' },
  { ticker: "SCHIFFY", theme: 'culture' },
  { ticker: "SCRVAN", theme: 'culture' },
  { ticker: "SDOG", theme: 'dogs' },
  { ticker: "SGI", theme: 'agents' },
  { ticker: "SHROOM", theme: 'culture' },
  { ticker: "si16z", theme: 'agents' },
  { ticker: "SIBUBBLE", theme: 'agents' },
  { ticker: "SIM", theme: 'agents' },
  { ticker: "Smit", theme: 'culture' },
  { ticker: "SMITHERS", theme: 'culture' },
  { ticker: "SNOW", theme: 'culture' },
  { ticker: "snowball", theme: 'culture' },
  { ticker: "SPCX", theme: 'culture' },
  { ticker: "SPCXx", theme: 'culture' },
  { ticker: "SPIN", theme: 'culture' },
  { ticker: "SPP", theme: 'culture' },
  { ticker: "SPSN", theme: 'culture' },
  { ticker: "SR", theme: 'culture' },
  { ticker: "STAR", theme: 'culture' },
  { ticker: "STICK", theme: 'culture' },
  { ticker: "Stickdog", theme: 'dogs' },
  { ticker: "Tanuki", theme: 'critters' },
  { ticker: "TED", theme: 'culture' },
  { ticker: "TEDDY", theme: 'critters' },
  { ticker: "Terminator", theme: 'agents' },
  { ticker: "test", theme: 'culture' },
  { ticker: "TI", theme: 'agents' },
  { ticker: "Tico", theme: 'culture' },
  { ticker: "TIDE", theme: 'culture' },
  { ticker: "TIE", theme: 'culture' },
  { ticker: "TOM", theme: 'culture' },
  { ticker: "Topless", theme: 'culture' },
  { ticker: "Town", theme: 'culture' },
  { ticker: "UFG", theme: 'culture' },
  { ticker: "uin", theme: 'culture' },
  { ticker: "UNEMPLOYED", theme: 'culture' },
  { ticker: "unicorn", theme: 'critters' },
  { ticker: "VAMPINU", theme: 'dogs' },
  { ticker: "VI", theme: 'agents' },
  { ticker: "VLADCAT", theme: 'cats' },
  { ticker: "VRAX", theme: 'culture' },
  { ticker: "W", theme: 'culture' },
  { ticker: "WAGMI", theme: 'culture' },
  { ticker: "wbECX", theme: 'culture' },
  { ticker: "WEENIETOWN", theme: 'culture' },
  { ticker: "Winter", theme: 'culture' },
  { ticker: "WOWWW", theme: 'culture' },
  { ticker: "Xoge", theme: 'culture' },
  { ticker: "XSI", theme: 'agents' },
  { ticker: "xSOL", theme: 'culture' },
  { ticker: "Yolk", theme: 'critters' },
  { ticker: "Yotsuba", theme: 'culture' },
  { ticker: "ZARA", theme: 'culture' },
  { ticker: "ZELENSKY", theme: 'culture' },
  { ticker: "ZERO", theme: 'culture' },
  { ticker: "ZILLI", theme: 'culture' },
  { ticker: "スズメ", theme: 'culture' },
  { ticker: "ツノミン", theme: 'culture' },
  { ticker: "娜娜", theme: 'culture' },
  { ticker: "楊澎澎", theme: 'culture' },
  { ticker: "나나", theme: 'culture' },
];

/** What kind of coin each theme is, for the terminal table. */
export const THEME_NOUN: Record<Theme, string> = {
  dogs: 'dog coin',
  cats: 'cat coin',
  critters: 'animal coin',
  agents: 'agent coin',
  culture: 'meme coin',
};

export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
